# coding: utf-8

"""
    Web Forms API version 1.1

    The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 

    The version of the OpenAPI document: 1.1.0
    Contact: devcenter@docusign.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_instance_request_body import CreateInstanceRequestBody

class TestCreateInstanceRequestBody(unittest.TestCase):
    """CreateInstanceRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateInstanceRequestBody:
        """Test CreateInstanceRequestBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateInstanceRequestBody`
        """
        model = CreateInstanceRequestBody()
        if include_optional:
            return CreateInstanceRequestBody(
                form_values = {Textbox_Name=First Last, Email_primary=example@example.com, Date_birth=2020-01-01, Number_age=52, Select_state=California, Radio_Gender=Female, Checkbox_hobbies=[singing, dancing]},
                client_user_id = 'customer_id@domain.com',
                authentication_instant = '',
                authentication_method = 'Biometric, Email, HTTPBasicAuth, Kerberos etc',
                assertion_id = 'client-12345',
                security_domain = '',
                return_url = 'http://www.thankyoupage.com',
                expiration_offset = 120,
                tags = [loan_application, finance_dept]
            )
        else:
            return CreateInstanceRequestBody(
                client_user_id = 'customer_id@domain.com',
        )
        """

    def testCreateInstanceRequestBody(self):
        """Test CreateInstanceRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
