# coding: utf-8

"""
    Web Forms API version 1.1

    The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 

    The version of the OpenAPI document: 1.1.0
    Contact: devcenter@docusign.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.web_form_source import WebFormSource

class TestWebFormSource(unittest.TestCase):
    """WebFormSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebFormSource(self):
        """Test WebFormSource"""
        # inst = WebFormSource()

if __name__ == '__main__':
    unittest.main()
