# coding: utf-8

"""
    Web Forms API version 1.1

    The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 

    The version of the OpenAPI document: 1.1.0
    Contact: devcenter@docusign.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.form_instance_management_api import FormInstanceManagementApi


class TestFormInstanceManagementApi(unittest.TestCase):
    """FormInstanceManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FormInstanceManagementApi()

    def tearDown(self) -> None:
        pass

    def test_create_instance(self) -> None:
        """Test case for create_instance

        Creates an instance of the web form
        """
        pass

    def test_get_instance(self) -> None:
        """Test case for get_instance

        Get form instance
        """
        pass

    def test_list_instances(self) -> None:
        """Test case for list_instances

        List instances
        """
        pass

    def test_refresh_token(self) -> None:
        """Test case for refresh_token

        Refreshes the instance token
        """
        pass


if __name__ == '__main__':
    unittest.main()
