# coding: utf-8

"""
    Web Forms API version 1.1

    The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 

    The version of the OpenAPI document: 1.1.0
    Contact: devcenter@docusign.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.web_form_instance import WebFormInstance

class TestWebFormInstance(unittest.TestCase):
    """WebFormInstance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebFormInstance:
        """Test WebFormInstance
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebFormInstance`
        """
        model = WebFormInstance()
        if include_optional:
            return WebFormInstance(
                form_url = 'https://webforms-ux/v1.0/forms/82356c8f286b4e4df592af7d0984f51d',
                instance_token = '',
                token_expiration_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '00000000-0000-0000-0000-000000000000',
                form_id = '00000000-0000-0000-0000-000000000000',
                account_id = '00000000-0000-0000-0000-000000000000',
                client_user_id = 'customer_id@domain.com',
                tags = [loan_application, finance_dept],
                status = 'INITIATED',
                envelopes = [
                    openapi_client.models.web_form_instance_envelopes_inner.WebFormInstance_envelopes_inner(
                        id = '00000000-0000-0000-0000-000000000000', )
                    ],
                instance_metadata = {expirationDateTime=2023-08-16T10:30:00Z, createdBy={userId=00000000-0000-0000-0000-000000000000, userName=DocuSign User}, createdDateTime=2023-08-15T10:30:00Z, lastModifiedBy={userId=00000000-0000-0000-0000-000000000000, userName=DocuSign User}, lastModifiedDateTime=2023-08-15T20:30:00Z},
                form_values = {Textbox_Name=First Last, Email_primary=example@example.com, Date_birth=2020-01-01, Number_age=52, Select_state=California, Radio_Gender=Female, Checkbox_hobbies=[singing, dancing]}
            )
        else:
            return WebFormInstance(
                id = '00000000-0000-0000-0000-000000000000',
        )
        """

    def testWebFormInstance(self):
        """Test WebFormInstance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
