# coding: utf-8

"""
    Web Forms API version 1.1

    The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 

    The version of the OpenAPI document: 1.1.0
    Contact: devcenter@docusign.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AuthenticationMethod(str, Enum):
    """
    A value that most closely matches the technique your application used to authenticate the recipient / signer.
    """

    """
    allowed enum values
    """
    BIOMETRIC = 'Biometric'
    EMAIL = 'Email'
    HTTPBASICAUTH = 'HTTPBasicAuth'
    KERBEROS = 'Kerberos'
    KNOWLEDGEBASEDAUTH = 'KnowledgeBasedAuth'
    NONE = 'None'
    PAPERDOCUMENTS = 'PaperDocuments'
    PASSWORD = 'Password'
    RSASECUREID = 'RSASecureID'
    SINGLE_SIGN_ON_CA_SITEMINDER = 'SingleSignOn_CASiteminder'
    SINGLE_SIGN_ON_INFO_CARD = 'SingleSignOn_InfoCard'
    SINGLE_SIGN_ON_MICROSOFT_ACTIVE_DIRECTORY = 'SingleSignOn_MicrosoftActiveDirectory'
    SINGLE_SIGN_ON_OTHER = 'SingleSignOn_Other'
    SINGLE_SIGN_ON_PASSPORT = 'SingleSignOn_Passport'
    SINGLE_SIGN_ON_SAML = 'SingleSignOn_SAML'
    SMARTCARD = 'Smartcard'
    SSLMUTUALAUTH = 'SSLMutualAuth'
    X509CERTIFICATE = 'X509Certificate'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AuthenticationMethod from a JSON string"""
        return cls(json.loads(json_str))


