# coding: utf-8

"""
    Web Forms API version 1.1

    The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 

    The version of the OpenAPI document: 1.1.0
    Contact: devcenter@docusign.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class InstanceSource(str, Enum):
    """
    The method through which form instance is created.
    """

    """
    allowed enum values
    """
    PUBLIC_URL = 'PUBLIC_URL'
    API_EMBEDDED = 'API_EMBEDDED'
    API_REMOTE = 'API_REMOTE'
    UI_REMOTE = 'UI_REMOTE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InstanceSource from a JSON string"""
        return cls(json.loads(json_str))


