# coding: utf-8

"""
    Web Forms API version 1.1

    The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 

    The version of the OpenAPI document: 1.1.0
    Contact: devcenter@docusign.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TemplateProperties(BaseModel):
    """
    Information about a DocuSign template that will be used to seed a web form.
    """ # noqa: E501
    original_template_id: Optional[StrictStr] = Field(default=None, alias="originalTemplateId")
    cloned_template_id: Optional[StrictStr] = Field(default=None, alias="clonedTemplateId")
    imported_date_time: Optional[datetime] = Field(default=None, description="Track the time of assignment of Template information to the Form.", alias="importedDateTime")
    recipient_ids: Optional[List[StrictStr]] = Field(default=None, description="Track mapped recipients on Template.", alias="recipientIds")
    __properties: ClassVar[List[str]] = ["originalTemplateId", "clonedTemplateId", "importedDateTime", "recipientIds"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TemplateProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TemplateProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "originalTemplateId": obj.get("originalTemplateId"),
            "clonedTemplateId": obj.get("clonedTemplateId"),
            "importedDateTime": obj.get("importedDateTime"),
            "recipientIds": obj.get("recipientIds")
        })
        return _obj


