# coding: utf-8

"""
    Web Forms API version 1.1

    The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 

    The version of the OpenAPI document: 1.1.0
    Contact: devcenter@docusign.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.web_form_user_info import WebFormUserInfo
from typing import Optional, Set
from typing_extensions import Self

class WebFormInstanceMetadata(BaseModel):
    """
    Web Form Instance metadata containing information like created by, created time, etc.
    """ # noqa: E501
    expiration_date_time: datetime = Field(description="The datetime after which the Web Form Instance is inaccessible.", alias="expirationDateTime")
    created_date_time: datetime = Field(description="The dateTime when the Web Form Instance is created.", alias="createdDateTime")
    created_by: WebFormUserInfo = Field(alias="createdBy")
    last_modified_date_time: Optional[datetime] = Field(default=None, description="The dateTime when the Web Form Instance is last modified.", alias="lastModifiedDateTime")
    last_modified_by: Optional[WebFormUserInfo] = Field(default=None, alias="lastModifiedBy")
    __properties: ClassVar[List[str]] = ["expirationDateTime", "createdDateTime", "createdBy", "lastModifiedDateTime", "lastModifiedBy"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebFormInstanceMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['createdBy'] = self.created_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of last_modified_by
        if self.last_modified_by:
            _dict['lastModifiedBy'] = self.last_modified_by.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebFormInstanceMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "expirationDateTime": obj.get("expirationDateTime"),
            "createdDateTime": obj.get("createdDateTime"),
            "createdBy": WebFormUserInfo.from_dict(obj["createdBy"]) if obj.get("createdBy") is not None else None,
            "lastModifiedDateTime": obj.get("lastModifiedDateTime"),
            "lastModifiedBy": WebFormUserInfo.from_dict(obj["lastModifiedBy"]) if obj.get("lastModifiedBy") is not None else None
        })
        return _obj


